name: Publish
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish
          env:
            APIKEY: ${{ secrets.CIMDISKIMAGE_APIKEY }}
          run: .\build\publish.ps1
          shell: pwsh